[package]
name = "arkworks_fft_benchmark"
version = "0.0.1"
authors = ["The Tachyon Authors <tachyon-discuss@kroma.network>"]
edition = "2021"
rust-version = "1.56.1"
description = """
Arkworks FFT Benchmark
"""
license = "MIT OR Apache-2.0"
repository = "https://github.com/kroma-network/tachyon"
readme = "README.md"
categories = ["cryptography"]
keywords = ["tachyon", "benchmark", "arkworks"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-test-curves = { git = "https://github.com/kroma-network/algebra.git", rev = "53f396c" }
ark-poly = { version = "0.4.2", features = ["parallel"] }
tachyon_rs = { path = "../../../tachyon/rs" }
